spring.application.name=psicotestes

spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/psicotestes
#spring.datasource.username=
#spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.sql.init.data-locations=classpath:users.sql, classpath:bdi_ii.sql

api.security.token.secret=${JWT_SECRET:psicotestes-secret-local-dev}